version: '2'
services:
  zookeeper:
    build: ./zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./kafka
    ports:
      #- "9092:9092"
      - "9095:9095"
  nginx:
    build: ./nginx
    ports:
      - "12345:12345"